# Generated by Django 4.1 on 2022-10-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_author_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(related_name='following', to='network.follow'),
        ),
    ]
